name: 'deploy_static_resources'

on:
  push:
    branches:
      - main
    paths:
      - static_resources/**
      - .github/workflows/static_resources.yml

permissions:
  contents: read

jobs:
  deploy_static_resources:
    name: 'deploy_static_resources'
    runs-on: ubuntu-latest
    environment: production
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Init
      working-directory: static_resources
      run: terraform init

    - name: Terraform Format
      working-directory: static_resources
      run: terraform fmt -check

    - name: Terraform Plan
      working-directory: static_resources
      run: terraform plan -input=false

    - name: Terraform Apply
      working-directory: static_resources
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
